### ISSUE TITLE
nr1 nerdpack:uuid -gf command not found 

### ISSUE THREAD

**Issue by Swathi4592** [newrelic/nr1-workshop#170]
Trying multiple ways but getting below error 

[root@srsbg3pnrlapp01 ~]# nr1 nerdpack:uuid -gf
-bash: nr1: command not found

[root@srsbg3pnrlapp01 nr1-wall-status-board]# nr1 nerdpack:uuid -gf
-bash: nr1: command not found
[root@srsbg3pnrlapp01 nr1-wall-status-board]#

**Comment by jdezego** [comment]
@Swathi4592 - You have to install the NR1 command line utility:

https://developer.newrelic.com/explore-docs/nr1-cli/
