### ISSUE TITLE
Lab 1 step 2 & 3 Qs

### ISSUE THREAD

**Issue by satan02** [newrelic/nr1-workshop#58]
Step 2 Bullets 2, 3, 4, 5, I tried doing a command f but it returns nothing since “CHARTS” area on the left is not expanded, I am using Chrome.

Step 3 bullet 4, I did this with my personal account which does not have any app data at the moment and get a “There was a problem…” message, I suspect clients may see this as well.

**Comment by jaesius** [comment]
Hi, here is a link to the component library and you can navigate it using the left navigation: https://developer.newrelic.com/client-side-sdk/index.html#components/AutoSizer

Also, in order for the charts to work, you will need to have data in your account.
