### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by satan02** [newrelic/nr1-workshop#60]
I think it would be good to add a snippet that each lab builds on the previous so you do not need to go through each lab and can jump ahead.  Also, it should be noted that the terminal window that runs either npm install or nr1 nerdpack:serve needs to be left open during the lab and how npm interacts with one.newrelic.com.

**Comment by jaesius** [comment]
Hi, some of the labs pick up where the previous one left off, but not all. Some of them are different, and they all focus on a different concept of building a New Relic One application.
