### ISSUE TITLE
Should nerdpack:uuid Effect the Published Version?

### ISSUE THREAD

**Issue by astormnewrelic** [newrelic/nr1-workshop#71]
The docs in Lab 10: https://github.com/newrelic/nr1-workshop/blob/master/lab-cli/INSTRUCTIONS.md

include this text

> The outcome of this command will be resetting the value of the package.json's version attribute to be a uuid value generated by the command.

However, after I run the command, it's the `nr1.uuid` attribute that's changed. 

    $ nr1 nerdpack:uuid -gf
    Generated id is 7a...47
    
    $ git diff
    diff --git a/package.json b/package.json
    index 5463a0d..79b4ed5 100644
    --- a/package.json
    +++ b/package.json
    @@ -8,7 +8,7 @@
         "test": "exit 0"
       },
       "nr1": {
    -    "uuid": "9f...48"
    +    "uuid": "7a...47"
       },
       "dependencies": {
         "prop-types": "^15.6.2",

i.e. my `version` attribute is untouched. 

Is the command incorrect/out-of-date, or are the docs incorrect/out-of-date? Or am I doing something wrong?

**Comment by jaesius** [comment]
Hi @astormnewrelic, the docs are out of date. Thanks for the heads up.
